


INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'AMAZONAS', 'AM');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'PARÁ', 'PA');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'MATO GROSSO', 'MT');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'MINAS GERAIS', 'MG');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'BAHIA', 'BA');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'MATO GROSSO DO SUL', 'MS');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'GOIAS', 'GO');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'MARANHÃO', 'MA');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'RIO GRANDE DO SUL', 'RS');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'TOCANTINS', 'TO');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'PIAUÍ', 'PI');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'SÃO PAULO', 'SP');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'RONDÔNIA', 'RO');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'RORAIMA', 'RR');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'PARANÁ', 'PR');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'ACRE', 'AC');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'CEARÁ', 'CE');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'AMAPÁ', 'AP');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'PERNAMBUCO', 'PE');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'SANTA CATARINA', 'SC');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'PARAÍBA', 'PB');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'RIO GRANDE DO NORTE', 'RN');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'ESPIRITO SANTO', 'ES');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'RIO DE JANEIRO', 'RJ');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'ALAGOAS', 'AL');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'SERGIPE', 'SE');

INSERT INTO T_AM_SCN_ESTADO
VALUES (SQ_AM_ESTADO.NEXTVAL, 'DISTRITO FEDERAL', 'DF');

SELECT * FROM T_AM_SCN_ESTADO;

--SP CIDADES--
INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 12, 'SÃO PAULO');  

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 12, 'CAMPINAS');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 12, 'SANTO ANDRÉ');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 12, 'SÃO BERNADO');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 12, 'SÃO CAETANO');

--RJ CIDADES--

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 24, 'RIO DE JANEIRO');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 24, 'ANGRA DOS REIS');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 24, 'CABO FRIO');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 24, 'RESENDE');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 24, 'NOVA IGUAÇU');

--MG CIDADES--

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 4, 'BELO HORIZONTE');  

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 4, 'CAETE');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 4, 'CONTAGEM');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 4, 'ESTRELA DE MINAS');

INSERT INTO T_AM_SCN_CIDADE
VALUES(SQ_SCN_CIDADE.NEXTVAL, 4, 'FRONTEIRA');  

SELECT * FROM T_AM_SCN_CIDADE;

-- SP BAIRROS --

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 1, 'MOOCA');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 1, 'ACLIMAÇÃO');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 1, 'CAMBUCI');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 1, 'TATUAPÉ');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 1, 'IPIRANGA');

-- RJ BAIRROS --

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 6, 'FLAMENGO');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 6, 'COPACABANA');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 6, 'GÁVEA');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 6, 'IPANEMA');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 6, 'LEBLON');

-- BELO HORIZONTE BAIRROS --

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 11, 'VILA FORMOSA');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 11, 'CRISTO REDENTOR');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 11, 'ITAIPU');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 11, 'MANGUEIRAS');

INSERT INTO T_AM_SCN_BAIRRO
VALUES(SQ_SCN_BAIRRO.NEXTVAL, 11, 'PETRÓPOLIS');

SELECT * FROM T_AM_SCN_BAIRRO;

-- tipo log--

INSERT INTO T_AM_SCN_TIPO_LOG
VALUES (SQ_SCN_TIPO_LOG.NEXTVAL, 'ALAMEDA');


INSERT INTO T_AM_SCN_TIPO_LOG
VALUES (SQ_SCN_TIPO_LOG.NEXTVAL, 'AVENIDA');


INSERT INTO T_AM_SCN_TIPO_LOG
VALUES (SQ_SCN_TIPO_LOG.NEXTVAL, 'PRAÇA');


INSERT INTO T_AM_SCN_TIPO_LOG
VALUES (SQ_SCN_TIPO_LOG.NEXTVAL, 'RUA');


INSERT INTO T_AM_SCN_TIPO_LOG
VALUES (SQ_SCN_TIPO_LOG.NEXTVAL, 'TRAVESSA');

SELECT * FROM T_AM_SCN_TIPO_LOG;

-- LOGRADOUROS ACLIMAÇÃO --
SELECT * FROM T_AM_SCN_BAIRRO;

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (01313001, 3, 'LINS DE VASCONCELOS', 2);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (01323001, 3, 'BRAZ CUBAS', 4);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (01323401, 3, 'XIMBO', 4);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (01353401, 3, 'DA ACLIMAÇÃO', 2);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (0136001, 3, 'SANTO AGOSTINHO', 3);

-- LOGRADOURO CAMBUCI--

SELECT * FROM T_AM_SCN_TIPO_LOG;

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (0136001, 3, 'AMARANTE', 4);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (0136001, 3, 'LAVAPES', 4);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (0136001, 3, 'DOM PEDRO I', 2);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (0136001, 3, 'HERMINIO LEMOS', 4);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (0136001, 3, 'ARNO', 2);

INSERT INTO T_AM_SCN_LOGRADOURO
VALUES (01313002, 8, 'NOVE DE JULHO' , 2); 


SELECT * FROM T_AM_SCN_LOGRADOURO;

--ADICIONAIS MAIS LOGRADOUROS---

-- TIPO FONE --

SELECT * FROM T_AM_SCN_TIPO_FONE;

INSERT INTO T_AM_SCN_TIPO_FONE
VALUES (SQ_SCN_TIPO_FONE.NEXTVAL, 'COMERCIAL');

INSERT INTO T_AM_SCN_TIPO_FONE
VALUES (SQ_SCN_TIPO_FONE.NEXTVAL, 'RESIDENCIAL');

INSERT INTO T_AM_SCN_TIPO_FONE
VALUES (SQ_SCN_TIPO_FONE.NEXTVAL, 'CELULAR');

INSERT INTO T_AM_SCN_TIPO_FONE
VALUES (SQ_SCN_TIPO_FONE.NEXTVAL, 'RECADOS');

-- TELEFONE --

SELECT * FROM T_AM_SCN_TELEFONE;

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 1, 11, 232322333);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 3, 11, 921839182);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 2, 11, 213890128);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 1, 18, 343432134);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 4, 86, 928329492);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 2, 44, 425435345);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 1, 8, 12313122);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 3, 11, 982131230);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 4, 26, 837487282);

INSERT INTO T_AM_SCN_TELEFONE
VALUES (SQ_SCN_TELEFONE.NEXTVAL, 2, 34, 123123131);

-- PESSOA --

INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'MARIA FLORES');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'JOAO ROSA');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'GUSMÃO ARRUDA');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'JOANA AMARAL');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'RUI BARBOSA');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'JANIO QUADROS');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'EUCLIDES DA CUNHA');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'GUIMARAES ROSA');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'JULIANA DO AMARAL');


INSERT INTO T_AM_SCN_PESSOA
VALUES (SQ_SCN_PESSOA.NEXTVAL, 'ROBERTO CARLOS');

SELECT * FROM T_AM_SCN_PESSOA;

-- PESSOA ENDEREÇO --

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1323401 , 1 , 240 , 'CASA A');

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1323401, 1, 400, NULL);

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1323401 , 2 , 86 , 'APTO 403');

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1323401, 2 , 89 , 'APTO 20' );

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1353401 , 3 , 5 , NULL );

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1353401 , 3 , 10 , 'CASA B');

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 136001 , 4 , 1954 , NULL );

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 136001 , 5 , 100 , 'CASA B' );

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 1313001, 6 , 2056 , 'APTO 105');

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 01313002 , 7 , 1943 ,'APTO 403');

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 01313002 , 8 , 143 ,'APTO 203');

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 01313002 , 9 , 13 ,NULL);

INSERT INTO T_AM_SCN_PESSOA_ENDE
VALUES (SQ_SCN_PESSOA_ENDE.NEXTVAL, 01313002 , 10 , 193 , 'BLOCO C - APTO 12');

SELECT * FROM T_AM_SCN_LOGRADOURO;

SELECT * FROM T_AM_SCN_PESSOA_ENDE;

-- FONE PESSOA --

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (1, 11, 1234);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (1, 12, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (2, 13, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (2, 14, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (3, 15, 354);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (3, 16, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (4, 17, 677);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (5, 18, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (5, 19, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (6, 20, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (6, 13, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (7, 11, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (7, 12, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (8, 15, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (9, 19, NULL);

INSERT INTO T_AM_SCN_PESSOA_FONE
VALUES (10, 20, NULL);

SELECT * FROM T_AM_SCN_TELEFONE;

SELECT * FROM T_AM_SCN_PESSOA_FONE;











