--Sequencias


/*DROP SEQUENCE SQ_SCN_ESTADO;
DROP SEQUENCE SQ_SCN_CIDADE;
DROP SEQUENCE SQ_SCN_BAIRRO;
DROP SEQUENCE SQ_SCN_TIPO_LOG;
DROP SEQUENCE SQ_SCN_LOGRADOURO;
DROP SEQUENCE SQ_SCN_TIPO_FONE;
DROP SEQUENCE SQ_SCN_TELEFONE;
DROP SEQUENCE SQ_SCN_PESSOA;
DROP SEQUENCE SQ_SCN_CLIENTE;
DROP SEQUENCE SQ_SCN_PESSOA_ENDE;
DROP SEQUENCE SQ_SCN_HBV_Reserva;
DROP SEQUENCE SQ_SCN_HBV_Quarto;
DROP SEQUENCE SQ_SCN_HBV_Tipo_Quarto;
DROP SEQUENCE SQ_SCN_HBV_Historico_valor;
DROP SEQUENCE SQ_SCN_HBV_Tipo_FormaPag;
DROP SEQUENCE SQ_SCN_HBV_Hospedagem;
DROP SEQUENCE SQ_SCN_HBV_Pagto_Cartao;
DROP SEQUENCE SQ_SCN_HBV_Pagto_cheque;
DROP SEQUENCE SQ_SCN_CONSUMO;
DROP SEQUENCE SQ_SCN_HBV_Tipo_Servico;
DROP SEQUENCE SQ_SCN_HBV_Hist_Preco_Produto;
DROP SEQUENCE SQ_SCN_HBV_HISTORICO_PRECO;*/

 
 --SEQUENCIAS
 
--SEQUENCIA TABELA ESTADO
CREATE SEQUENCE SQ_SCN_ESTADO
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA CIDADE
CREATE SEQUENCE SQ_SCN_CIDADE
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA BAIRRO
CREATE SEQUENCE SQ_SCN_BAIRRO
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA TIPO LOGRADOURO
CREATE SEQUENCE SQ_SCN_TIPO_LOG
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

--SQEUENCIA TABELA LOGRADOURO
CREATE SEQUENCE SQ_SCN_LOGRADOURO
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA TIPO TELEFONE
CREATE SEQUENCE SQ_SCN_TIPO_FONE
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA TELEFONE
CREATE SEQUENCE SQ_SCN_TELEFONE
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA PESSOA
CREATE SEQUENCE SQ_SCN_PESSOA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA CLIENTE --
CREATE SEQUENCE SQ_SCN_CLIENTE
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;


--SEQUENCIA TABELA PESSOA ENDERECO
CREATE SEQUENCE SQ_SCN_PESSOA_ENDE
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA RESERVA
CREATE SEQUENCE SQ_SCN_HBV_Reserva
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA QUARTO
CREATE SEQUENCE SQ_SCN_HBV_Quarto
INCREMENT BY 1
START WITH 1
MAXVALUE 9999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA TIPO DO QUARTO
CREATE SEQUENCE SQ_SCN_HBV_Tipo_Quarto
INCREMENT BY 1
START WITH 1
MAXVALUE 99
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA DO HISTORICO DE VALOR
CREATE SEQUENCE SQ_SCN_HBV_Historico_valor
INCREMENT BY 1
START WITH 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA DO TIPO DE FORMA DE PAGAMENTO
CREATE SEQUENCE SQ_SCN_HBV_Tipo_FormaPag
INCREMENT BY 1
START WITH 1
MAXVALUE 9
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA HOSPEDAGEM
CREATE SEQUENCE SQ_SCN_HBV_Hospedagem
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA PAGAMENTO NO CARTAO
CREATE SEQUENCE SQ_SCN_HBV_Pagto_Cartao
INCREMENT BY 1
START WITH 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA PAGAMENTO EM CHEQUE
CREATE SEQUENCE SQ_SCN_HBV_Pagto_cheque
INCREMENT BY 1
START WITH 1
MAXVALUE 999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA CONSUMO
CREATE SEQUENCE SQ_SCN_CONSUMO
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA DO TIPO DE SERVICO
CREATE SEQUENCE SQ_SCN_HBV_Tipo_Servico
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;


--SEQUENCIA TABELA DO HISTÓRICO DO PREÇO--
CREATE SEQUENCE SQ_SCN_HBV_HISTORICO_PRECO
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

--SEQUENCIA TABELA DO HISTORICO DO PRECO PRODUTO
CREATE SEQUENCE SQ_SCN_HBV_Hist_Preco_Produto
INCREMENT BY 1
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;



